name: Auto PR Workflow

on:
  push:
    branches:
      - 'feature/*'
  pull_request:
    branches:
      - develop
      - release/*

jobs:
  create-pr-to-develop:
    if: startsWith(github.ref_name, 'feature/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Pull Request to Develop
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: develop
          branch: ${{ github.ref_name }}
          title: 'Auto: Merge feature to develop'
          body: 'Automatically created pull request from feature branch.'

  create-release-branch-and-pr:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'develop'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Determine release version
        id: get_version
        run: |
          echo "release_version=$(date +'%Y.%m.%d')" >> $GITHUB_ENV

      - name: Create release branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout develop
          git checkout -b release/${{ steps.get_version.outputs.release_version }}
          git push origin release/${{ steps.get_version.outputs.release_version }}

      - name: Create Pull Request to Release
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: release/${{ steps.get_version.outputs.release_version }}
          branch: develop
          title: 'Auto: Merge develop to release'
          body: 'Automatically created pull request from develop to release.'

  create-pr-to-main:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.base.ref, 'release/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Pull Request to Main
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: ${{ github.event.pull_request.base.ref }}
          title: 'Auto: Merge release to main'
          body: 'Automatically created pull request from release to main.'
