name: Auto PR Workflow

on:
  push:
    branches:
      - 'feature/*'
  pull_request:
    types: [closed]

jobs:
  auto-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Pull Request to Develop
        if: startsWith(github.ref_name, 'feature/')
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: develop
          branch: ${{ github.ref_name }}
          title: 'Auto: Merge feature to develop'
          body: 'Automatically created pull request from feature branch.'

      - name: Create Release Branch and PR
        if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'develop'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout develop
          release_version=$(date +'%Y.%m.%d')
          git checkout -b release/${release_version}
          git push origin release/${release_version}
          gh pr create --base release/${release_version} --head develop --title "Auto: Merge develop to release" --body "Automatically created pull request from develop to release."

      - name: Create PR to Main
        if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.base.ref, 'release/')
        run: |
          gh pr create --base main --head ${{ github.event.pull_request.base.ref }} --title "Auto: Merge release to main" --body "Automatically created pull request from release to main."