name: Auto PR feature to develop

on:
  push:
    branches:
      - 'feature/*'
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        
    - name: Install dependencies
      run: npm install --non-interactive

  open-pr:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        branch: feature-branch
        base: develop
        title: 'Auto PR from feature to develop'
        body: 'This is an automated pull request from feature to develop'