name: PR Feature / test

on:
  push:
    branches:
      - feature/**
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup C compiler
        id: install_cc
        uses: rlalik/setup-cpp-compiler@master
        with:
          compiler: latest

      - name: Make
        shell: bash
        run: make all

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ft_cli
          path: ${{ github.workspace }}/ft
          if-no-files-found: error