name: PR Feature / test

on:
  push:
    branches:
      - feature/**
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup C compiler
        id: install_cc
        uses: rlalik/setup-cpp-compiler@master
        with:
          compiler: latest

      - name: Test
        shell: bash
        run: |
          pwd
          ls -la
          echo "${{ github.workspace }}"