name: PR Feature / test

on:
  push:
    branches:
      - feature/**
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: PR to Develop
        uses: desbravacloud/action-create-pull-requests@v1
        with:
          origin-branch: '${{ github.head_ref}}'
          target-branch: 'develop'
          custom-title: 'PR created'
          custom-body: 'Please, check thease changes'